# General application settings
general:
  # Monitoring interval in seconds
  monitoring_interval: 10

# Server settings
server:
  host: "0.0.0.0"  # Listen on all network interfaces
  port: 8000       # Port to run the server on

# Serial port device paths for each logical port ID
serial_ports:
  0: /dev/ttyAMA5
  1: /dev/ttyAMA2
  2: /dev/ttyAMA4
  3: /dev/ttyAMA0

port_labels:
  0: "BH2"
  1: "BAC"
  2: "KVC-1"
  3: "KVC-2"

databases:
  db_directory: "data"
  db_suffix: ""

# Test mode setting
test_mode:
  # Set to true to run in test mode (simulated hardware)
  # Set to false to run with real hardware
  enabled: False