DEBUG: true

# HV limit setting [V]
VMAX_MODULE1: 60
VMAX_MODULE2: 60
VMAX_MODULE3: 60
VMAX_MODULE4: 60

# temp correction parameter
V0: 50 # V
T0: 20 # deg
DELTA_T_HIGH: 0         # mv/deg
DELTA_T_HIGH_PRIME: 0   # mv/deg^2
DELTA_T_LOW: 0          # mv/deg
DELTA_T_LOW_PRIME: 0    # mv/deg^2

# interval time setting [sec]
PLOT_INTERVAL: 5
MONITORING_INTERVAL: 5

# database setting
SQLALCHEMY_DATABASE_URI: "sqlite:///log.db"
SQLALCHEMY_BINDS:
  mppc_data: "sqlite:///mppc_data.db"
SQLALCHEMY_TRACK_MODIFICATIONS: false
SQLALCHEMY_ECHO: false
